---
title: "test"
author: "James Street"
date: "2024-05-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(robotstxt)
library(rvest)
library(purrr)
library(polite)
library(Stat2Data)
library(dplyr)
library(mosaic)
library(tidyverse)
library(ggplot2)
library(gridExtra)
library(stringr)
library(stringi)
```

```{r}
transfer <- read.csv("data/Final_TransferData.csv")
stats <- read.csv("data/Final_PlayerStats")

transfer <- transfer %>%
  select(short_name, Position, Transfer.Price..Millions.)

transfer_noGK <- transfer %>%
                      filter(Position != "Goalkeeper")

Final_Combined <- inner_join(transfer_noGK, stats, by = "short_name")

colnames(Final_Combined)[3] <- "TransferPrice"

write.csv(Final_Combined, file = "Final_Combined.csv")

missing <- anti_join(transfer_noGK, stats, by = "short_name")

defender <- Final_Combined %>%
              filter(Position == "Defender")

# Create a dataset for midfielders
midfielder <- Final_Combined %>%
                filter(Position == "Midfielder")

# Create a dataset for attackers
attacker <- Final_Combined %>%
              filter(Position == "Attacker")



```

```{r}


# Perform MLR for defenders
mlr_defender <- lm(TransferPrice ~ defending + pace + physic, data = defender)

# Perform MLR for midfielders
mlr_midfielder <- lm(TransferPrice ~ pace + shooting + passing + dribbling + defending + physic, data = midfielder)

# Perform MLR for attackers
mlr_attacker <- lm(TransferPrice ~ pace + shooting + passing + dribbling + defending + physic, data = attacker)

# Print the summary of each regression model
summary(mlr_defender)
summary(mlr_midfielder)
summary(mlr_attacker)
```

```{r}
# Define a function to perform simple linear regression for each variable
perform_simple_regression <- function(defender) {
  # List to store regression results
  regression_results <- list()
  
  # Get explanatory variable names
  predictor_vars <- colnames(defender)[9:15]
  
  # Iterate over each explanatory variable
  for (var in predictor_vars) {
    # Define formula for simple linear regression
    formula <- as.formula(paste("TransferPrice ~", var))
    
    # Fit simple linear regression model
    lm_model <- lm(formula, data = defender)
    
    # Store regression results
    regression_results[[var]] <- lm_model
  }
  
  # Return the list of regression results
  return(regression_results)
}

# Perform simple linear regression for the 'defenders' dataset
defender_regression <- perform_simple_regression(defender)

# Print the summary of the first regression model for the 'defenders' dataset

for (i in 1:6) {
  print(summary(defender_regression[[i]]))
}
```


```{r}
perform_simple_regression <- function(midfielder) {
  # List to store regression results
  regression_results <- list()
  
  # Get explanatory variable names
  predictor_vars <- colnames(midfielder)[9:15]
  
  # Iterate over each explanatory variable
  for (var in predictor_vars) {
    # Define formula for simple linear regression
    formula <- as.formula(paste("TransferPrice ~", var))
    
    # Fit simple linear regression model
    lm_model <- lm(formula, data = midfielder)
    
    # Store regression results
    regression_results[[var]] <- lm_model
  }
  
  # Return the list of regression results
  return(regression_results)
}

# Perform simple linear regression for the 'defenders' dataset
midfielder_regression <- perform_simple_regression(midfielder)

# Print the summary of the first regression model for the 'defenders' dataset

for (i in 1:6) {
  print(summary(midfielder_regression[[i]]))
}


```

```{r}
regression_test <- midfielder %>%
  select(TransferPrice, shooting, pace, dribbling, defending, physic, passing)

model <- lm(TransferPrice ~ shooting + pace + dribbling + defending + physic + passing, data = regression_test)

msummary(model)

model2 <- lm(TransferPrice ~ shooting + pace + dribbling + defending + passing, data = regression_test)

msummary(model2)

model3 <- lm(TransferPrice ~ shooting + pace + defending + passing, data = regression_test)

msummary(model3)

# Perform automated variable selection
```


```{r}
perform_simple_regression <- function(attacker) {
  # List to store regression results
  regression_results <- list()
  
  # Get explanatory variable names
  predictor_vars <- colnames(attacker)[9:15]
  
  # Iterate over each explanatory variable
  for (var in predictor_vars) {
    # Define formula for simple linear regression
    formula <- as.formula(paste("TransferPrice ~", var))
    
    # Fit simple linear regression model
    lm_model <- lm(formula, data = attacker)
    
    # Store regression results
    regression_results[[var]] <- lm_model
  }
  
  # Return the list of regression results
  return(regression_results)
}

# Perform simple linear regression for the 'defenders' dataset
attacker_regression <- perform_simple_regression(attacker)

# Print the summary of the first regression model for the 'defenders' dataset

for (i in 1:6) {
  print(summary(attacker_regression[[i]]))
}
```

```{r}
ggplot(Final_Combined, aes(x = shooting)) + geom_histogram(fill="lightblue", color="black", bins = 30) +
  labs(title="Distribution of Variable", x="Variable Values", y="Frequency")

ggplot(Final_Combined, aes(x = pace)) + geom_histogram(fill="lightblue", color="black", bins = 30) +
  labs(title="Distribution of Variable", x="Variable Values", y="Frequency")

ggplot(Final_Combined, aes(x = passing)) + geom_histogram(fill="lightblue", color="black", bins = 30) +
  labs(title="Distribution of Variable", x="Variable Values", y="Frequency")

ggplot(Final_Combined, aes(x = physic)) + geom_histogram(fill="lightblue", color="black", bins = 30) +
  labs(title="Distribution of Variable", x="Variable Values", y="Frequency")


ggplot(Final_Combined, aes(x = dribbling)) + geom_histogram(fill="lightblue", color="black", bins = 30) +
  labs(title="Distribution of Variable", x="Variable Values", y="Frequency")

ggplot(Final_Combined, aes(x = defending)) + geom_histogram(fill="lightblue", color="black", bins = 30) +
  labs(title="Distribution of Variable", x="Variable Values", y="Frequency")
```
```{r}
ggplot(defender, aes(x = shooting)) + geom_histogram(fill="lightblue", color="black", bins = 30) +
  labs(title="Distribution of Variable", x="Variable Values", y="Frequency")

ggplot(defender, aes(x = pace)) + geom_histogram(fill="lightblue", color="black", bins = 30) +
  labs(title="Distribution of Variable", x="Variable Values", y="Frequency")

ggplot(defender, aes(x = passing)) + geom_histogram(fill="lightblue", color="black", bins = 30) +
  labs(title="Distribution of Variable", x="Variable Values", y="Frequency")

ggplot(defender, aes(x = physic)) + geom_histogram(fill="lightblue", color="black", bins = 30) +
  labs(title="Distribution of Variable", x="Variable Values", y="Frequency")


ggplot(defender, aes(x = dribbling)) + geom_histogram(fill="lightblue", color="black", bins = 30) +
  labs(title="Distribution of Variable", x="Variable Values", y="Frequency")

ggplot(defender, aes(x = defending)) + geom_histogram(fill="lightblue", color="black", bins = 30) +
  labs(title="Distribution of Variable", x="Variable Values", y="Frequency")
```
```{r}
ggplot(midfielder, aes(x = shooting)) + geom_histogram(fill="lightblue", color="black", bins = 30) +
  labs(title="Distribution of Variable", x="Variable Values", y="Frequency")

ggplot(midfielder, aes(x = pace)) + geom_histogram(fill="lightblue", color="black", bins = 30) +
  labs(title="Distribution of Variable", x="Variable Values", y="Frequency")

ggplot(midfielder, aes(x = passing)) + geom_histogram(fill="lightblue", color="black", bins = 30) +
  labs(title="Distribution of Variable", x="Variable Values", y="Frequency")

ggplot(midfielder, aes(x = physic)) + geom_histogram(fill="lightblue", color="black", bins = 30) +
  labs(title="Distribution of Variable", x="Variable Values", y="Frequency")


ggplot(midfielder, aes(x = dribbling)) + geom_histogram(fill="lightblue", color="black", bins = 30) +
  labs(title="Distribution of Variable", x="Variable Values", y="Frequency")

ggplot(midfielder, aes(x = defending)) + geom_histogram(fill="lightblue", color="black", bins = 30) +
  labs(title="Distribution of Variable", x="Variable Values", y="Frequency")
```
```{r}
ggplot(defender, aes(x = shooting)) + geom_histogram(fill="lightblue", color="black", bins = 30) +
  labs(title="Distribution of Variable", x="Variable Values", y="Frequency")

ggplot(defender, aes(x = pace)) + geom_histogram(fill="lightblue", color="black", bins = 30) +
  labs(title="Distribution of Variable", x="Variable Values", y="Frequency")

ggplot(defender, aes(x = passing)) + geom_histogram(fill="lightblue", color="black", bins = 30) +
  labs(title="Distribution of Variable", x="Variable Values", y="Frequency")

ggplot(defender, aes(x = physic)) + geom_histogram(fill="lightblue", color="black", bins = 30) +
  labs(title="Distribution of Variable", x="Variable Values", y="Frequency")


ggplot(defender, aes(x = dribbling)) + geom_histogram(fill="lightblue", color="black", bins = 30) +
  labs(title="Distribution of Variable", x="Variable Values", y="Frequency")

ggplot(defender, aes(x = defending)) + geom_histogram(fill="lightblue", color="black", bins = 30) +
  labs(title="Distribution of Variable", x="Variable Values", y="Frequency")
```

```{r}
ggplot(attacker, aes(x = shooting)) + geom_histogram(fill="lightblue", color="black", bins = 30) +
  labs(title="Distribution of Variable", x="Variable Values", y="Frequency")

ggplot(attacker, aes(x = pace)) + geom_histogram(fill="lightblue", color="black", bins = 30) +
  labs(title="Distribution of Variable", x="Variable Values", y="Frequency")

ggplot(attacker, aes(x = passing)) + geom_histogram(fill="lightblue", color="black", bins = 30) +
  labs(title="Distribution of Variable", x="Variable Values", y="Frequency")

ggplot(attacker, aes(x = physic)) + geom_histogram(fill="lightblue", color="black", bins = 30) +
  labs(title="Distribution of Variable", x="Variable Values", y="Frequency")


ggplot(attacker, aes(x = dribbling)) + geom_histogram(fill="lightblue", color="black", bins = 30) +
  labs(title="Distribution of Variable", x="Variable Values", y="Frequency")

ggplot(attacker, aes(x = defending)) + geom_histogram(fill="lightblue", color="black", bins = 30) +
  labs(title="Distribution of Variable", x="Variable Values", y="Frequency")
```

