---
title: "AllWrangling"
author: "James Street"
date: "2024-05-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(robotstxt)
library(rvest)
library(purrr)
library(polite)
library(Stat2Data)
library(dplyr)
library(mosaic)
library(tidyverse)
library(ggplot2)
library(gridExtra)

```

```{r}
url <- "https://www.transfermarkt.co.uk/premier-league/transfers/wettbewerb/GB1/plus/?saison_id=2023&s_w=&leihe=0&intern=0&intern=1"

# 2. Confirm bots are allowed to access the page 
paths_allowed(url)

# 3. Scrape tables on the page
tables <- url %>%
  read_html() %>%
  html_elements("table") #html_nodes can work as well, elements is newer

# 4. Identify and "pluck" tables you want to work with
table1 <- pluck(tables, 2) %>% 
  html_table()

table2 <- pluck(tables, 4) %>% 
  html_table()

table3 <- pluck(tables, 6) %>% 
  html_table()

table4 <- pluck(tables, 8) %>% 
  html_table()

table5<- pluck(tables, 10) %>% 
  html_table()

table6<- pluck(tables, 12) %>% 
  html_table()

table7<- pluck(tables, 14) %>% 
  html_table()

table8<- pluck(tables, 16) %>% 
  html_table()

table9<- pluck(tables, 18) %>% 
  html_table()

table10<- pluck(tables, 20) %>% 
  html_table()

table11<- pluck(tables, 22) %>% 
  html_table()

table12<- pluck(tables, 24) %>% 
  html_table()

table13<- pluck(tables, 26) %>% 
  html_table()

table14<- pluck(tables, 28) %>% 
  html_table()

table15<- pluck(tables, 30) %>% 
  html_table()

table16<- pluck(tables, 32) %>% 
  html_table()

table17<- pluck(tables, 34) %>% 
  html_table()

table18<- pluck(tables, 36) %>% 
  html_table()

table19<- pluck(tables, 38) %>% 
  html_table()

table20<- pluck(tables, 40) %>% 
  html_table()

table_list <- list()

for (i in seq(2, length(tables), by = 2)) {
  table <- tables[i] %>% html_table()
  table_list[[length(table_list) + 1]] <- table
}
transfer_table <- bind_rows(table_list, .id = "source_table")

# Optionally, you can assign meaningful names to the tables
names(transfer_table) <- paste0("table", seq_along(table_list))

transfer_table1 <- transfer_table %>%
  select(table2, table3, table5, table7, table9, table10) %>%
  rename(
    "short_name" = table2,
    "Age" = table3,
    "Position" = table5,
    "ExpectedValue" = table7,
    "Seller" = table9,
    "TransferPrice" = table10
    
  ) %>%
  mutate(Expected_Value2 = parse_number(ExpectedValue)) %>%
  mutate(TransferPrice2 = parse_number(TransferPrice))
#Case_when command was recommended to us in STD fellows

experiment <- transfer_table1 %>%
  mutate(Expected_Value3 = case_when(str_detect(ExpectedValue, "k") ~ Expected_Value2/1000, TRUE ~ Expected_Value2))

experiment2 <- experiment %>%
  mutate(TransferPrice3 = 
           case_when(str_detect(TransferPrice, "k") ~ TransferPrice2/1000, TRUE ~ TransferPrice2))

Final_Graph <- experiment2 %>%
  select(short_name, TransferPrice3, Position) %>%
  rename(
    "Transfer Price (Millions)" = TransferPrice3
  )

```

```{r}
Final_TransferData <- Final_Graph %>%
  na.omit()


#Final_TransferData$short_name <- str_extract(Final_TransferData$short_name, "[A-Z]\\.\\s?[A-Z][a-z]+")

changes <- list(
  `8` = "J. Gauci",
  `21` = "J. Pedro",
  `24` = "Igor",
  `33` = "D. O'Shea",
  `43` = "R. Sanchez",
  `45` = "D. Washington",
  `46` = "Angelo",
  `49` = "M. Franca",
  `53` = "Beto",
  `54` = "Chermiti",
  `77` = "R. Hojlund",
  `89` = "Murillo",
  `92` = "M. Sels",
  `101` = "I. Grbic",
  `105` = "M. van de Ven",
  `109` = "A. Veliz",
  `112` = "E. Alvarez",
  `120` = "E. Gonzalez"
)

# Loop through the changes and update the dataset
for (row_num in names(changes)) {
  name_to_replace <- changes[[row_num]]
  Final_TransferData$short_name[as.integer(row_num)] <- name_to_replace
}

Final_TransferData$short_name <- str_extract(Final_TransferData$short_name, "[A-Z]\\.\\s?[A-Z][a-z]+")

changes1 <- list(
  `8` = "J. Gauci",
  `10` = "H. Traore",
  `21` = "J. Pedro",
  `24` = "Igor",
  `33` = "D. O'Shea",
  `43` = "R. Sanchez",
  `45` = "D. Washington",
  `46` = "Angelo",
  `49` = "M. Franca",
  `51` = "D. Munoz",
  `53` = "Beto",
  `54` = "Chermiti",
  `58` = "R. Jimenez",
  `61` = "A. Mac Allister",
  `77` = "R. Hojlund",
  `80` = "A. Bayindir",
  `85` = "I. Sangare",
  `89` = "Murillo",
  `90` = "N. Dominguez",
  `92` = "M. Sels",
  `94` = "C. Hudson-Odoi",
  `99` = "B. Traore",
  `101` = "I. Grbic",
  `105` = "M. Van De Ven",
  `107` = "R. Dragusin",
  `109` = "A. Veliz",
  `112` = "E. Alvarez",
  `113` = "J. Ward-Prowse",
  `119` = "B. Traore"
)

# Loop through the changes and update the dataset
for (row_num in names(changes1)) {
  name_to_replace <- changes1[[row_num]]
  Final_TransferData$short_name[as.integer(row_num)] <- name_to_replace
}



```
```{r}
Final_TransferData <- Final_TransferData %>%
  mutate(Position = case_when(
    Position == "Goalkeeper" ~ "Goalkeeper",
    Position %in% c("Centre-Back", "Left-Back", "Right-Back") ~ "Defender",
    Position %in% c("Central Midfield", "Defensive Midfield", "Attacking Midfield", "Right Midfield") ~ "Midfielder",
    Position %in% c("Left Winger", "Right Winger", "Centre-Forward") ~ "Attacker",
    TRUE ~ "Other"
  ))
```

