---
title: "Untitled"
author: "James Street"
date: "2024-04-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(mosaic)
library(Stat2Data)
library(leaps)
library(broom)
library(rvest)
library(methods)
library(GGally)
```


```{r}
transfers <- transfer_table1 
  transfers$Buyer <- NA
transfers$Buyer[1:3] <- "Arsenal"
transfers$Buyer[4:11] <- "Aston Villa"
transfers$Buyer[12:18] <- "AFC Bournemouth"
transfers$Buyer[19:25] <- "Brentford"
transfers$Buyer[26:40] <- "Brighton & Hove Albion"
transfers$Buyer[41:53] <- "Burnley"
transfers$Buyer[54:70] <- "Chelsea"
transfers$Buyer[71:76] <- "Crystal Palace"
transfers$Buyer[77:82] <- "Everton"
transfers$Buyer[83:90] <- "Fulham"
transfers$Buyer[91:97] <- "Liverpool"
transfers$Buyer[98:110] <- "Luton Town"
transfers$Buyer[111:117] <- "Manchester City"
transfers$Buyer[118:124] <- "Manchester United"
transfers$Buyer[125:129] <- "Newcastle United"
transfers$Buyer[130:140] <- "Nottingham Forest"
transfers$Buyer[141:151] <- "Sheffield United"
transfers$Buyer[152:162] <- "Tottenham Hotspur"
transfers$Buyer[163:168] <- "West Ham United"
transfers$Buyer[169:175] <- "Wolverhampton Wanderers"

transfers <- na.omit(transfers)

transfers <- transfers[transfers$TransferPrice != "€870k", ]

transfers <- transfers %>%
  select(Name, Age, Position, Seller, TransferPrice2, Buyer) 

transfers <- transfers %>%
  rename(
    "TransferPriceMillionsEuros" = TransferPrice2
  )

```

